# Generated by Django 5.2.2 on 2025-12-26 23:04

from django.db import migrations
from django.utils.text import slugify


def populate_slugs(apps, schema_editor):
    """Populate slugs for existing projects"""
    Project = apps.get_model('portfolio', 'Project')
    for project in Project.objects.all():
        if not project.slug:
            base_slug = slugify(project.title)
            slug = base_slug
            counter = 1
            while Project.objects.filter(slug=slug).exists():
                slug = f"{base_slug}-{counter}"
                counter += 1
            project.slug = slug
            project.save()


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_alter_project_options_project_completion_date_and_more'),
    ]

    operations = [
        migrations.RunPython(populate_slugs),
    ]
